<a href="https://colab.research.google.com/github/naveen-colab/CNN_traffic_sign_classification/blob/main/trafic_sign_clssification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import cv2
import tensorflow as tf
import os
from PIL import Image
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout

In [ ]:
path_to_img = r'/content/drive/My Drive/ai_proj'
p = os.path.join(path_to_img+'/Test/00001.png')
j = Image.open(p)
plt.imshow(j)
o = o.resize((30,30))
im_resize=np.reshape(o,(2700,1))
temp = []
temp.append(im_resize.reshape(30,30,3))
print(np.array(temp).shape)

In [ ]:
path_to_img

NameError: ignored

In [ ]:
import PIL as image
#testing accuracy on test dataset
from sklearn.metrics import accuracy_score
test_y = pd.read_csv(r'/content/drive/My Drive/ai_proj/Test.csv')
labels = test_y["ClassId"]
imgs = test_y["Path"].values
cur_path = r'/content/drive/My Drive/ai_proj'
p = os.path.join(cur_path)
test_labels = []
k = []
print(labels.shape)
for j in range(len(imgs)):
  if labels[j] < 22:
    i = imgs[j]
    o = Image.open(p +'/'+i)
    o = o.resize((30,30))
    im_resize=np.reshape(o,(2700,1))
    temp = []
    temp.append(im_resize.reshape(30,30,3))
   # res=np.argmax(model.predict(np.array(temp)))
    k.append(labels[j])
    #test_labels.append(res)

(730,)


KeyboardInterrupt: ignored

In [ ]:
from google.colab import drive  #code  to access the googele drive
drive.mount("/content/drive")  #and mount it

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls

drive  sample_data


In [ ]:
cur_path = os.getcwd()    #to get the current working directory
print("Current working directory %s" % cur_path)
os.chdir(r"/content/drive/My Drive/ai_proj")  #changing the path to the train dataset in the drive 
cur_path = os.getcwd()     #
print("Current working directory %s" % cur_path)

Current working directory /content
Current working directory /content/drive/My Drive/ai_proj


In [ ]:
data = []                #code to access the images and 
labels = []              #and converting them into arrays 
classes = 43             
#Retrieving the images and their labels 
for i in range(22):
    path = os.path.join(cur_path,'train21',str(i))
    images = os.listdir(path)
    k=len(images)
    print(len(images))

    for a in images:
              image = Image.open(path + '//'+ a)
              image = image.resize((30,30))
              image = np.array(image)
              data.append(image)
              labels.append(i)
    print(i)
#Converting lists into numpy arrays
data = np.array(data)
labels = np.array(labels)

In [ ]:
with np.printoptions(threshold=np.inf):
    print(data[0:21])

[[[[ 67  63  63]
   [ 68  66  65]
   [ 79  70  66]
   [135  94  88]
   [172  98  97]
   [176  63  59]
   [187  91  76]
   [228 190 183]
   [254 243 252]
   [245 244 255]
   [240 243 254]
   [225 232 251]
   [164 167 194]
   [151 151 164]
   [215 207 210]
   [152 140 137]
   [139 126 131]
   [212 204 231]
   [231 233 253]
   [232 232 240]
   [229 227 238]
   [239 202 215]
   [176 109 104]
   [144  53  37]
   [167  81  77]
   [132 102  99]
   [ 94  86  77]
   [ 76  70  63]
   [ 68  65  61]
   [ 68  67  63]]

  [[ 69  67  67]
   [ 72  67  68]
   [100  84  80]
   [177 117 110]
   [179  89  78]
   [163  60  49]
   [213 138 129]
   [250 231 229]
   [254 251 255]
   [244 246 255]
   [244 245 255]
   [210 209 218]
   [142 132 139]
   [183 170 183]
   [244 238 255]
   [209 207 233]
   [123 124 155]
   [137 141 177]
   [216 221 245]
   [230 232 240]
   [236 233 244]
   [242 220 229]
   [221 175 169]
   [177  89  72]
   [152  54  33]
   [160  92  74]
   [145 109  98]
   [ 89  84  77]
   [ 71  72 

In [ ]:
print(np.shape(data))
labels = labels[:len(data)]
print(np.shape(labels))

(27310, 30, 30, 3)
(27310,)


In [ ]:
print(data.shape , labels.shape)

#Splitting training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

#Converting the labels into one hot encoding
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

(27310, 30, 30, 3) (27310,)
(21848, 30, 30, 3) (5462, 30, 30, 3) (21848,) (5462,)


In [ ]:
#Building the model
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(22, activation='softmax'))

#Compilation of the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 15
history = model.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))
model.save("matrix_model.h5")


Epoch 1/15
683/683 [==============================] - 90s 131ms/step - loss: 2.8186 - accuracy: 0.3271 - val_loss: 0.5066 - val_accuracy: 0.8691
Epoch 2/15
683/683 [==============================] - 89s 131ms/step - loss: 0.7691 - accuracy: 0.7715 - val_loss: 0.2634 - val_accuracy: 0.9297
Epoch 3/15
683/683 [==============================] - 89s 130ms/step - loss: 0.5606 - accuracy: 0.8327 - val_loss: 0.2494 - val_accuracy: 0.9421
Epoch 4/15
683/683 [==============================] - 89s 130ms/step - loss: 0.4388 - accuracy: 0.8666 - val_loss: 0.1287 - val_accuracy: 0.9616
Epoch 5/15
683/683 [==============================] - 89s 130ms/step - loss: 0.3718 - accuracy: 0.8879 - val_loss: 0.1028 - val_accuracy: 0.9714
Epoch 6/15
683/683 [==============================] - 89s 131ms/step - loss: 0.2652 - accuracy: 0.9214 - val_loss: 0.0736 - val_accuracy: 0.9786
Epoch 7/15
683/683 [==============================] - 89s 130ms/step - loss: 0.2416 - accuracy: 0.9263 - val_loss: 0.1096 - val_ac

In [ ]:
model.evaluate(X_test,y_test)

171/171 [==============================] - 5s 30ms/step - loss: 0.0982 - accuracy: 0.9705


[0.09824226051568985, 0.9705235958099365]

In [ ]:
import PIL as image

test_y = pd.read_csv('Test.csv')
labels = test_y["ClassId"].values
imgs = test_y["Path"].values

In [ ]:
cur_path = r'/content/drive/My Drive/ai_proj'
p = os.path.join(cur_path)
test_labels = []
k = []

for j in range(len(imgs)):
  if labels[j]<22:        
    i = imgs[j]
    o = Image.open(p +'/'+i)    #to open the image following the path
    o = o.resize((30,30))
    im_resize=np.reshape(o,(2700,1)) #resize the shape
    temp = []
    temp.append(im_resize.reshape(30,30,3))
    res=np.argmax(model.predict(np.array(temp)))
    k.append(labels[j])       #storing the labels of the images
    test_labels.append(res)  #storing the labels predicted by the model

In [ ]:
k

In [ ]:
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import confusion_matrix

#confusion matrix 

def plot_matrix(y_true,pred_y):
    matrix_labels = unique_labels(k)
    matrix_columns = [f'Predicted{label}' for label in matrix_labels]
    matrix_indexs = [f'Actual {label}' for label in matrix_labels]
    matrix_table = pd.DataFrame(confusion_matrix(y_true,pred_y),matrix_columns,matrix_indexs)
    return matrix_table

In [ ]:
plot_matrix(k,test_labels)

NameError: ignored

In [ ]:
for i in range(len(k)):
  if k[i] != test_labels[i]:
    print(k[i],test_labels[i])

In [ ]:
lt = Image.open(p+'/Test/00056.png')
lt = lt.resize((30,30))
im_resize=np.reshape(lt,(2700,1)) #resize the shape
temp = []
temp.append(im_resize.reshape(30,30,3))
res=np.argmax(model.predict(np.array(temp)))
print(res)

5


In [ ]:
print(len(test_labels),len(k))

506 507


In [ ]:
#Accuracy with the test data
from sklearn.metrics import accuracy_score
print(accuracy_score(k[:506], test_labels))

0.045454545454545456


In [ ]:
model2 = Sequential()
model2.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model2.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model2.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model2.add(MaxPool2D(pool_size=(2, 2)))
model2.add(Dropout(rate=0.25))
model2.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model2.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model2.add(MaxPool2D(pool_size=(2, 2)))
model2.add(Dropout(rate=0.25))
model2.add(Flatten())
model2.add(Dense(256, activation='relu'))
model2.add(Dropout(rate=0.5))
model2.add(Dense(43, activation='softmax'))

#Compilation of the model
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 5
history = model2.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))
#model2.save("my_model.h5")


Epoch 1/5
150/150 [==============================] - 28s 183ms/step - loss: 5.3795 - accuracy: 0.1155 - val_loss: 1.4798 - val_accuracy: 0.6357
Epoch 2/5
150/150 [==============================] - 27s 183ms/step - loss: 1.5477 - accuracy: 0.5164 - val_loss: 0.5902 - val_accuracy: 0.8367
Epoch 3/5
150/150 [==============================] - 27s 183ms/step - loss: 0.8055 - accuracy: 0.7558 - val_loss: 0.2109 - val_accuracy: 0.9464
Epoch 4/5
150/150 [==============================] - 28s 184ms/step - loss: 0.4680 - accuracy: 0.8497 - val_loss: 0.1404 - val_accuracy: 0.9631
Epoch 5/5
150/150 [==============================] - 27s 183ms/step - loss: 0.4711 - accuracy: 0.8815 - val_loss: 0.0719 - val_accuracy: 0.9832


In [ ]:
model2.evaluate(X_test,y_test)

38/38 [==============================] - 2s 40ms/step - loss: 0.0719 - accuracy: 0.9832


[0.07191582769155502, 0.9832496047019958]

In [ ]:
model3 = Sequential()
model3.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model3.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model3.add(MaxPool2D(pool_size=(2, 2)))
model3.add(Dropout(rate=0.25))
model3.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model3.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model3.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model3.add(MaxPool2D(pool_size=(2, 2)))
model3.add(Dropout(rate=0.25))
model3.add(Flatten())
model3.add(Dense(256, activation='relu'))
model3.add(Dropout(rate=0.5))
model3.add(Dense(43, activation='softmax'))

#Compilation of the model
model3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 5
history = model3.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))

Epoch 1/5
150/150 [==============================] - 22s 141ms/step - loss: 4.4747 - accuracy: 0.1486 - val_loss: 1.0414 - val_accuracy: 0.7647
Epoch 2/5
150/150 [==============================] - 21s 140ms/step - loss: 1.1824 - accuracy: 0.6476 - val_loss: 0.3969 - val_accuracy: 0.9330
Epoch 3/5
150/150 [==============================] - 21s 141ms/step - loss: 0.6091 - accuracy: 0.8252 - val_loss: 0.2904 - val_accuracy: 0.9481
Epoch 4/5
150/150 [==============================] - 21s 142ms/step - loss: 0.3789 - accuracy: 0.8979 - val_loss: 0.1139 - val_accuracy: 0.9816
Epoch 5/5
150/150 [==============================] - 21s 141ms/step - loss: 0.2490 - accuracy: 0.9294 - val_loss: 0.0754 - val_accuracy: 0.9858


In [ ]:
model3.evaluate(X_test,y_test)

38/38 [==============================] - 1s 32ms/step - loss: 0.0754 - accuracy: 0.9858


[0.07536090910434723, 0.9857621192932129]

In [ ]:
model4 = Sequential()
model4.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model4.add(MaxPool2D(pool_size=(2, 2)))
model4.add(Dropout(rate=0.25))
model4.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model4.add(MaxPool2D(pool_size=(2, 2)))
model4.add(Dropout(rate=0.25))
model4.add(Flatten())
model4.add(Dense(256, activation='relu'))
model4.add(Dropout(rate=0.5))
model4.add(Dense(43, activation='softmax'))

#Compilation of the model
model4.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 5
history = model4.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))

Epoch 1/5
150/150 [==============================] - 8s 47ms/step - loss: 17.0172 - accuracy: 0.1290 - val_loss: 1.6068 - val_accuracy: 0.5553
Epoch 2/5
150/150 [==============================] - 7s 46ms/step - loss: 1.7962 - accuracy: 0.4557 - val_loss: 0.6963 - val_accuracy: 0.8291
Epoch 3/5
150/150 [==============================] - 7s 46ms/step - loss: 1.0182 - accuracy: 0.6866 - val_loss: 0.4281 - val_accuracy: 0.9154
Epoch 4/5
150/150 [==============================] - 7s 45ms/step - loss: 0.6690 - accuracy: 0.7980 - val_loss: 0.2568 - val_accuracy: 0.9581
Epoch 5/5
150/150 [==============================] - 7s 46ms/step - loss: 0.5197 - accuracy: 0.8393 - val_loss: 0.1692 - val_accuracy: 0.9631


In [ ]:
model4.evaluate(X_test,y_test)

38/38 [==============================] - 1s 13ms/step - loss: 0.0818 - accuracy: 0.9757


[0.08180870860815048, 0.9757118821144104]

In [ ]:
model5 = Sequential()
model5.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model5.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model5.add(MaxPool2D(pool_size=(2, 2)))
model5.add(Dropout(rate=0.25))
model5.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model5.add(MaxPool2D(pool_size=(2, 2)))
model5.add(Dropout(rate=0.25))
model5.add(Flatten())
model5.add(Dense(256, activation='relu'))
model5.add(Dropout(rate=0.5))
model5.add(Dense(43, activation='softmax'))

#Compilation of the model
model5.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 5
history = model5.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))

Epoch 1/5
150/150 [==============================] - 7s 46ms/step - loss: 0.4119 - accuracy: 0.8750 - val_loss: 0.1546 - val_accuracy: 0.9757
Epoch 2/5
150/150 [==============================] - 7s 45ms/step - loss: 0.3196 - accuracy: 0.9056 - val_loss: 0.1487 - val_accuracy: 0.9774
Epoch 3/5
150/150 [==============================] - 7s 45ms/step - loss: 0.3223 - accuracy: 0.9121 - val_loss: 0.0906 - val_accuracy: 0.9858
Epoch 4/5
150/150 [==============================] - 7s 45ms/step - loss: 0.2559 - accuracy: 0.9265 - val_loss: 0.0829 - val_accuracy: 0.9841
Epoch 5/5
150/150 [==============================] - 7s 46ms/step - loss: 0.2419 - accuracy: 0.9273 - val_loss: 0.0802 - val_accuracy: 0.9866


In [ ]:
model5.evaluate(X_test,y_test)

38/38 [==============================] - 1s 29ms/step - loss: 25.9283 - accuracy: 0.0191


[25.58661651611328, 0.024288106709718704]

In [ ]:
model6 = Sequential()
model6.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model6.add(MaxPool2D(pool_size=(2, 2)))
model6.add(Dropout(rate=0.25))
model6.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model6.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model6.add(MaxPool2D(pool_size=(2, 2)))
model6.add(Dropout(rate=0.25))
model6.add(Flatten())
model6.add(Dense(256, activation='relu'))
model6.add(Dropout(rate=0.5))
model6.add(Dense(43, activation='softmax'))

#Compilation of the model
model6.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 15
history = model6.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))

Epoch 1/15
150/150 [==============================] - 10s 66ms/step - loss: 10.1036 - accuracy: 0.1539 - val_loss: 0.9655 - val_accuracy: 0.7722
Epoch 2/15
150/150 [==============================] - 10s 63ms/step - loss: 1.2477 - accuracy: 0.6303 - val_loss: 0.2985 - val_accuracy: 0.9414
Epoch 3/15
150/150 [==============================] - 9s 63ms/step - loss: 0.5865 - accuracy: 0.8316 - val_loss: 0.2042 - val_accuracy: 0.9665
Epoch 4/15
150/150 [==============================] - 9s 63ms/step - loss: 0.4359 - accuracy: 0.8675 - val_loss: 0.1484 - val_accuracy: 0.9707
Epoch 5/15
150/150 [==============================] - 10s 64ms/step - loss: 0.3101 - accuracy: 0.9175 - val_loss: 0.1616 - val_accuracy: 0.9749
Epoch 6/15
150/150 [==============================] - 10s 64ms/step - loss: 0.2878 - accuracy: 0.9101 - val_loss: 0.0763 - val_accuracy: 0.9807
Epoch 7/15
150/150 [==============================] - 10s 64ms/step - loss: 0.2558 - accuracy: 0.9302 - val_loss: 0.0409 - val_accuracy: 

In [ ]:
model6.evaluate(X_test,y_test)

38/38 [==============================] - 1s 16ms/step - loss: 0.0072 - accuracy: 0.9983


[0.007162950932979584, 0.9983249306678772]

In [ ]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(43, activation='softmax'))

#Compilation of the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 15
history = model.fit(X_train, y_train, batch_size=32, epochs=epochs, validation_data=(X_test, y_test))
model.save("my_model.h5")


Epoch 1/15
150/150 [==============================] - 21s 137ms/step - loss: 5.7970 - accuracy: 0.1506 - val_loss: 1.2869 - val_accuracy: 0.7261
Epoch 2/15
150/150 [==============================] - 20s 136ms/step - loss: 1.3693 - accuracy: 0.5969 - val_loss: 0.7162 - val_accuracy: 0.8459
Epoch 3/15
150/150 [==============================] - 20s 136ms/step - loss: 0.9399 - accuracy: 0.7232 - val_loss: 0.4972 - val_accuracy: 0.9146
Epoch 4/15
150/150 [==============================] - 21s 137ms/step - loss: 0.6628 - accuracy: 0.8049 - val_loss: 0.3135 - val_accuracy: 0.9363
Epoch 5/15
150/150 [==============================] - 21s 137ms/step - loss: 0.5561 - accuracy: 0.8367 - val_loss: 0.2718 - val_accuracy: 0.9531
Epoch 6/15
150/150 [==============================] - 21s 137ms/step - loss: 0.4839 - accuracy: 0.8619 - val_loss: 0.2899 - val_accuracy: 0.9288
Epoch 7/15
150/150 [==============================] - 21s 138ms/step - loss: 0.5461 - accuracy: 0.8485 - val_loss: 0.1983 - val_ac

In [ ]:
model.evaluate(X_test,y_test)

In [ ]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(43, activation='softmax'))

#Compilation of the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
epochs = 15
history = model.fit(X_train, y_train, batch_size=64, epochs=epochs, validation_data=(X_test, y_test))
model.save("my_model.h5")


In [ ]:
epochs

NameError: ignored